-- MySQL Script generated by MySQL Workbench
-- Mon Jun 13 10:29:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cdpadilla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cdpadilla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cdpadilla` ;
USE `cdpadilla` ;

-- -----------------------------------------------------
-- Table `cdpadilla`.`cdp_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdpadilla`.`cdp_usuarios` (
  `IDUSUARIO` VARCHAR(22) NOT NULL,
  `NOMBREUSUARIO` VARCHAR(199) NOT NULL,
  `CORREOUSUARIO` VARCHAR(199) NOT NULL,
  `PASSUSUARIO` VARCHAR(199) NOT NULL,
  PRIMARY KEY (`IDUSUARIO`),
  UNIQUE INDEX `IDUSER_UNIQUE` (`IDUSUARIO` ASC) VISIBLE,
  UNIQUE INDEX `CORREOUSUARIO_UNIQUE` (`CORREOUSUARIO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdpadilla`.`cdp_prefijos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdpadilla`.`cdp_prefijos` (
  `IDPREFIJO` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`IDPREFIJO`),
  UNIQUE INDEX `IDPREFIJO_UNIQUE` (`IDPREFIJO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdpadilla`.`cdp_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdpadilla`.`cdp_facturas` (
  `IDFACTURA` VARCHAR(22) NOT NULL,
  `NUIPFACTURA` VARCHAR(16) NOT NULL,
  `NOMBREFACTURA` VARCHAR(199) NOT NULL,
  `CONCEPTOFACTURA` VARCHAR(299) NOT NULL,
  `VALORFACTURA` INT NOT NULL,
  `FECHAFACTURA` DATE NOT NULL,
  `VENCIMIENTOFACTURA` DATE NOT NULL,
  PRIMARY KEY (`IDFACTURA`),
  UNIQUE INDEX `IDRECIBO_UNIQUE` (`IDFACTURA` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cdpadilla`.`cdp_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdpadilla`.`cdp_pagos` (
  `cdp_facturas_IDFACTURA` VARCHAR(22) NOT NULL,
  `ESTADOPAGO` TINYINT(2) NOT NULL,
  `TIPODOCPAGO` VARCHAR(4) NOT NULL,
  `NUIPPAGO` VARCHAR(16) NOT NULL,
  `NOMBREPAGO` VARCHAR(199) NOT NULL,
  `CORREOPAGO` VARCHAR(199) NOT NULL,
  `TELEFONOPAGO` VARCHAR(11) NULL,
  `REFEPAYCO` VARCHAR(48) NOT NULL,
  `APIEPAYCO` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`cdp_facturas_IDFACTURA`),
  UNIQUE INDEX `cdp_facturas_IDFACTURA_UNIQUE` (`cdp_facturas_IDFACTURA` ASC) VISIBLE,
  CONSTRAINT `fk_cdp_pagos_cdp_facturas`
    FOREIGN KEY (`cdp_facturas_IDFACTURA`)
    REFERENCES `cdpadilla`.`cdp_facturas` (`IDFACTURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
